version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-dubnium
    container_name: selenium-hub
    network_mode: "host"
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:3.141.59-dubnium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    network_mode: "host"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  parseinst:
    depends_on:
      - firefox
    network_mode: "host"
    build: .